--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KingDbrm/Enderchest-vPro
build-by-default: true
branches:
  - main
projects:
  Enderchest-vPro:
   libs:
      - src: muqsit/InvMenu/InvMenu
        branch: pm5
        version: ^4.6.3
      - src: muqsit\customsizedinvmenu\CustomSizedInvMenu
        version: ^2.0.0
...
